name: crawler
on:
  schedule:
    - cron:  '* */4 * * *'
jobs:
  commits_crawler:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: cd commits && npx prisma generate
    - run: npm run commits:run
